### ISSUE TITLE
mainwindow.cpp issue in qtcreator

### ISSUE THREAD

**Issue by ahmedawad1** [dudmuck/sx127x_qt#1]
Hi,
I am totally new to LoRa and I am trying to understand it. The project is very interesting.
i followed the steps to get the GUI running but when building the project. i get a problem in the "mainwindow.cpp" in the usleep(20000) function at line 1099. how to get it declared in this scope?

When I comment the usleep function, the code builds and run. I know it is not so important now, it will make no difference as understanding the code is really tough.

**Comment by dudmuck** [comment]
The system header files must have changed.  usleep() requires unistd.h
The commit has been made.
